#!/bin/sh
#
# $FreeBSD$
#

# PROVIDE: ix-etc
# REQUIRE: dispatcher etcd
# BEFORE: FILESYSTEMS

. /etc/rc.subr

etc_start()
{
	/usr/local/sbin/dispatcherctl call plugin.wait_for_service '"etcd.generation"'
	#/usr/local/sbin/dispatcherctl call etcd.generation.generate_all

	# Generate just the groups we are currently using
	/usr/local/sbin/dispatcherctl call etcd.generation.generate_group '"services"'
	/usr/local/sbin/dispatcherctl call etcd.generation.generate_group '"accounts"'
	/usr/local/sbin/dispatcherctl call etcd.generation.generate_group '"localtime"'
	/usr/local/sbin/dispatcherctl call etcd.generation.generate_group '"nginx"'
	/usr/local/sbin/dispatcherctl call etcd.generation.generate_group '"crypto"'
	/usr/local/sbin/dispatcherctl call etcd.generation.generate_group '"console"'

	/usr/local/sbin/dispatcherctl call etcd.generation.generate_group '"afp"'
	/usr/local/sbin/dispatcherctl call etcd.generation.generate_group '"dyndns"'
	/usr/local/sbin/dispatcherctl call etcd.generation.generate_group '"ftp"'
	/usr/local/sbin/dispatcherctl call etcd.generation.generate_group '"samba"'
	#killall -ALRM sh
}

name="ix-etc"
start_cmd='etc_start'
stop_cmd=':'
status_cmd=':'

load_rc_config $name
run_rc_command $*
