#!/bin/sh
#
# $FreeBSD$
#

# PROVIDE: containerd
# REQUIRE: datastore dispatcher

. /etc/rc.subr

name="containerd"
rcvar="containerd_enable"
pidfile="/var/run/containerd.pid"
command="/usr/sbin/daemon"
start_precmd="prestart"

prestart()
{
    rc_flags="-P ${pidfile} -f -r /usr/local/sbin/crash-wrapper /usr/local/sbin/containerd ${rc_flags}"
}

load_rc_config $name
run_rc_command $*
