#!/bin/sh
#
# $FreeBSD$
#

# PROVIDE: networkd
# REQUIRE: datastore dispatcher
# BEFORE: FILESYSTEMS

. /etc/rc.subr

name="networkd"
rcvar="networkd_enable"
pidfile="/var/run/networkd.pid"
command="/usr/sbin/daemon"
start_precmd="prestart"

prestart()
{
    rc_flags="-P ${pidfile} -f -r /usr/local/sbin/crash-wrapper /usr/local/sbin/networkd ${rc_flags}"
}

load_rc_config $name
run_rc_command $*